### ISSUE TITLE
Menu to select video device

### ISSUE THREAD

**Issue by alexarje** [fourMs/AudioVideoAnalysis#30]
Would be nice to be able to select video device in a menu similar to for the audio device.

**Comment by aleksati** [comment]
So just to be clear, make a pop-up-window for the video settings like the image below instead of the umenus which are there now, @alexarje ?
![Annotation 2020-04-25 222025](https://user-images.githubusercontent.com/54307488/80290040-21ed9b80-8743-11ea-8525-bd0c882220c5.jpg)

**Comment by alexarje** [comment]
No, I looked at the wrong patch. I think what you have now looks good!
